---
output:
  word_document: default
  html_document: default
---
# Module 4 - Assignment 2
## Kiser, Stephen
### Data Cleansing

```{r Loading in tidyverse and dataset}
library(tidyverse)
library(readxl)
CustomerChurn <- read_excel("CustomerChurn.xlsx",
 col_types = c("text", "text", "text",
 "text", "numeric", "text", "text",
 "text", "text", "text", "text", "text",
 "text", "text", "text", "text", "text",
 "numeric", "numeric", "text"))
```

#### Cleaning Missing Data
```{r Cleaning Missing Data}
summary(CustomerChurn)

CustomerChurn2 <- mutate(CustomerChurn,MonthlyCharges = replace(MonthlyCharges, is.nan(MonthlyCharges), median(MonthlyCharges, na.rm = TRUE)))

CustomerChurn2 <- mutate(CustomerChurn2,TotalCharges = replace(TotalCharges, is.na(TotalCharges), mean(TotalCharges, na.rm = TRUE)))

CustomerChurn2 <- mutate(CustomerChurn2,PaymentMethod = replace(PaymentMethod, is.na(PaymentMethod), "ElectronicCheck"))

```

#### Part 2 - Outliers
```{r Outliers}
boxplot(CustomerChurn2$tenure)
boxplot(CustomerChurn2$tenure)$out

outliers <- boxplot(CustomerChurn2$tenure)$out
CustomerChurn2[which(CustomerChurn2$tenure %in% outliers),]

CustomerChurn3 <- CustomerChurn2[-which(CustomerChurn2$tenure %in% outliers),]

boxplot(CustomerChurn3$tenure)

```

